#!/usr/bin/python3
from sys import argv


def sqrt(x):
    return x ** 0.5


with open(argv[1]) as f:
    for line in f:
        num = int(line)
        print("{:d}=".format(num), end="")
        if num % 2 == 0:
            print("{}*2".format(num//2))
            continue
        for q in range(3, int(sqrt(num)+1), 2):
            if num % q == 0:
                p = num // q
                print("{}*{}".format(p, q))
                break
