#!/usr/bin/python3
import sys


def sqrt(x):
    """ Calculates the square root of x """
    return int(x ** 0.5)


with open(sys.argv[1]) as f:
    for line in f:
        num = int(line)
        print("{}=".format(num), end="")

        if num % 2 == 0:
            print("{}*2".format(num // 2))
            continue

        for q in range(3, sqrt(num) + 1, 2):
            if num % q == 0:
                p = num // q
                print("{}*{}".format(p, q))
                break
        else:
            print("{}*1".format(num))
